directories:
  output: dist-electron
  buildResources: build
appId: com.wincleaner.app
productName: WinCleaner
win:
  target: portable
  icon: electron/assets/icon.ico
publish:
  provider: github
  owner: Shawn-huang86
  repo: wincleaner
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
extraResources:
  - from: electron/assets
    to: assets
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: WinCleaner
asar: false
electronVersion: 37.2.6
